# Generated by Django 4.2.6 on 2023-11-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('authname', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
